USE master
GO

-- CREA LA BASE DE DATOS SI NO EXISTE
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'CSTIBDPRUEBA')
BEGIN
    CREATE DATABASE CSTIBDPRUEBA
    PRINT 'Base de datos CSTIBDPRUEBA creada exitosamente.'
END
ELSE
BEGIN
    PRINT 'La base de datos CSTIBDPRUEBA ya existe.'
END
GO

--USAR BASE DATOS
USE CSTIBDPRUEBA
GO

--CREA TABLA
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MOV_INVENTARIO]') AND type in (N'U'))
BEGIN
		CREATE TABLE dbo.MOV_INVENTARIO(
		COD_CIA varchar(5) NOT NULL,
		COMPANIA_VENTA_3 varchar(5) NOT NULL,
		ALMACEN_VENTA varchar(10) NOT NULL,
		TIPO_MOVIMIENTO varchar(2) NOT NULL,
		TIPO_DOCUMENTO varchar(2) NOT NULL,
		NRO_DOCUMENTO varchar(50) NOT NULL,
		COD_ITEM_2 varchar(50) NOT NULL,
		PROVEEDOR varchar(100) NULL,
		ALMACEN_DESTINO varchar(50) NULL,
		CANTIDAD int NULL,
		DOC_REF_1 varchar(50) NULL,
		DOC_REF_2 varchar(50) NULL,
		DOC_REF_3 varchar(50) NULL,
		DOC_REF_4 varchar(50) NULL,
		DOC_REF_5 varchar(50) NULL,
		FECHA_TRANSACCION DATE NULL,
		CONSTRAINT PK_MOV_INVENTARIO PRIMARY KEY CLUSTERED
		(
		COD_CIA ASC,
		COMPANIA_VENTA_3 ASC,
		ALMACEN_VENTA ASC,
		TIPO_MOVIMIENTO ASC,
		TIPO_DOCUMENTO ASC,
		NRO_DOCUMENTO ASC,
		COD_ITEM_2 ASC
		)  )
		ON [PRIMARY]
		
END

GO
--INSERTA DATO PRUEBA
IF NOT EXISTS (SELECT 1 FROM dbo.MOV_INVENTARIO)
BEGIN
	INSERT INTO dbo.MOV_INVENTARIO
	(
		COD_CIA,
		COMPANIA_VENTA_3,
		ALMACEN_VENTA,
		TIPO_MOVIMIENTO,
		TIPO_DOCUMENTO,
		NRO_DOCUMENTO,
		COD_ITEM_2,
		PROVEEDOR,
		ALMACEN_DESTINO,
		CANTIDAD,
		DOC_REF_1,
		DOC_REF_2,
		DOC_REF_3,
		DOC_REF_4,
		DOC_REF_5,
		FECHA_TRANSACCION
	)
	VALUES
	(
		'CIA01',
		'CV01',
		'ALM001',
		'IN',          -- Tipo Movimiento
		'FA',          -- Tipo Documento
		'DOC000001',
		'ITEM001',
		'Proveedor ABC SAC',
		'ALM002',
		100,
		'REF001',
		'REF002',
		NULL,
		NULL,
		NULL,
		'2026-02-06'
	);
END
GO
--LISTA DATOS
CREATE OR ALTER PROCEDURE SP_MOV_INVENTARIO_LISTAR

	@FECHA_INICIO DATE = NULL,
    @FECHA_FIN DATE = NULL,
    @TIPO_MOVIMIENTO VARCHAR(2) = NULL,
    @NRO_DOCUMENTO VARCHAR(50) = NULL

AS

BEGIN
	SET NOCOUNT ON;
	SELECT  
        COD_CIA,
        COMPANIA_VENTA_3,
        ALMACEN_VENTA,
        TIPO_MOVIMIENTO,
        TIPO_DOCUMENTO,
        NRO_DOCUMENTO,
        COD_ITEM_2,
        PROVEEDOR,
        ALMACEN_DESTINO,
        CANTIDAD,
        DOC_REF_1,
        DOC_REF_2,
        DOC_REF_3,
        DOC_REF_4,
        DOC_REF_5,
        FECHA_TRANSACCION
    FROM dbo.MOV_INVENTARIO
	WHERE
        (@FECHA_INICIO IS NULL OR FECHA_TRANSACCION >= @FECHA_INICIO)
    AND (@FECHA_FIN IS NULL OR FECHA_TRANSACCION <= @FECHA_FIN)
    AND (@TIPO_MOVIMIENTO IS NULL OR TIPO_MOVIMIENTO = @TIPO_MOVIMIENTO)
    AND (@NRO_DOCUMENTO IS NULL OR NRO_DOCUMENTO = @NRO_DOCUMENTO)
    ORDER BY FECHA_TRANSACCION DESC;


END

GO
--OBTIENE DATOS POR PRIMARY KEY
CREATE OR ALTER PROCEDURE SP_MOV_INVENTARIO_OBTENER

@COD_CIA		  varchar(5)  ,
@COMPANIA_VENTA_3 varchar(5)  ,
@ALMACEN_VENTA	  varchar(10) ,
@TIPO_MOVIMIENTO  varchar(2)  ,
@TIPO_DOCUMENTO   varchar(2)  ,
@NRO_DOCUMENTO    varchar(50) ,
@COD_ITEM_2		  varchar(50)

AS

BEGIN
	SET NOCOUNT ON;
	SELECT  
        COD_CIA,
        COMPANIA_VENTA_3,
        ALMACEN_VENTA,
        TIPO_MOVIMIENTO,
        TIPO_DOCUMENTO,
        NRO_DOCUMENTO,
        COD_ITEM_2,
        PROVEEDOR,
        ALMACEN_DESTINO,
        CANTIDAD,
        DOC_REF_1,
        DOC_REF_2,
        DOC_REF_3,
        DOC_REF_4,
        DOC_REF_5,
        FECHA_TRANSACCION
    FROM dbo.MOV_INVENTARIO
	WHERE  COD_CIA = @COD_CIA AND
        COMPANIA_VENTA_3 = @COMPANIA_VENTA_3 AND
        ALMACEN_VENTA = @ALMACEN_VENTA AND
        TIPO_MOVIMIENTO = @TIPO_MOVIMIENTO AND
        TIPO_DOCUMENTO = @TIPO_DOCUMENTO AND
        NRO_DOCUMENTO = @NRO_DOCUMENTO AND
        COD_ITEM_2 = @COD_ITEM_2
    ORDER BY FECHA_TRANSACCION DESC;


END

GO
--REGISTRA DATOS
CREATE OR ALTER PROCEDURE SP_MOV_INVENTARIO_INSERTAR 

@COD_CIA		  varchar(5)  ,
@COMPANIA_VENTA_3 varchar(5)  ,
@ALMACEN_VENTA	  varchar(10) ,
@TIPO_MOVIMIENTO  varchar(2)  ,
@TIPO_DOCUMENTO   varchar(2)  ,
@NRO_DOCUMENTO    varchar(50) ,
@COD_ITEM_2		  varchar(50),
@PROVEEDOR		  varchar(100) ,
@ALMACEN_DESTINO  varchar(50) ,
@CANTIDAD		  int ,
@DOC_REF_1		  varchar(50) ,
@DOC_REF_2        varchar(50) ,
@DOC_REF_3        varchar(50) ,
@DOC_REF_4        varchar(50) ,
@DOC_REF_5        varchar(50) ,
@FECHA_TRANSACCION DATE 
AS

BEGIN
	SET NOCOUNT ON;

	INSERT INTO dbo.MOV_INVENTARIO (
		COD_CIA,
        COMPANIA_VENTA_3,
        ALMACEN_VENTA,
        TIPO_MOVIMIENTO,
        TIPO_DOCUMENTO,
        NRO_DOCUMENTO,
        COD_ITEM_2,
        PROVEEDOR,
        ALMACEN_DESTINO,
        CANTIDAD,
        DOC_REF_1,
        DOC_REF_2,
        DOC_REF_3,
        DOC_REF_4,
        DOC_REF_5,
        FECHA_TRANSACCION
	)
	VALUES(  
        @COD_CIA,
        @COMPANIA_VENTA_3,
        @ALMACEN_VENTA,
        @TIPO_MOVIMIENTO,
        @TIPO_DOCUMENTO,
        @NRO_DOCUMENTO,
        @COD_ITEM_2,
        @PROVEEDOR,
        @ALMACEN_DESTINO,
        @CANTIDAD,
        @DOC_REF_1,
        @DOC_REF_2,
        @DOC_REF_3,
        @DOC_REF_4,
        @DOC_REF_5,
        @FECHA_TRANSACCION )


END

GO
--ACTUALIZA DATOS
CREATE OR ALTER PROCEDURE  SP_MOV_INVENTARIO_ACTUALIZAR

@COD_CIA		  varchar(5)  ,
@COMPANIA_VENTA_3 varchar(5)  ,
@ALMACEN_VENTA	  varchar(10) ,
@TIPO_MOVIMIENTO  varchar(2)  ,
@TIPO_DOCUMENTO   varchar(2)  ,
@NRO_DOCUMENTO    varchar(50) ,
@COD_ITEM_2		  varchar(50),
@PROVEEDOR		  varchar(100) ,
@ALMACEN_DESTINO  varchar(50) ,
@CANTIDAD		  int ,
@DOC_REF_1		  varchar(50) ,
@DOC_REF_2        varchar(50) ,
@DOC_REF_3        varchar(50) ,
@DOC_REF_4        varchar(50) ,
@DOC_REF_5        varchar(50) ,
@FECHA_TRANSACCION DATE 

AS

BEGIN
	SET NOCOUNT ON;

	UPDATE dbo.MOV_INVENTARIO
		SET PROVEEDOR = @PROVEEDOR  ,
			ALMACEN_DESTINO = @ALMACEN_DESTINO ,
			CANTIDAD = @CANTIDAD		,
			DOC_REF_1 = @DOC_REF_1		,
			DOC_REF_2 = @DOC_REF_2		,
			DOC_REF_3 = @DOC_REF_3		,
			DOC_REF_4 = @DOC_REF_4		,
			DOC_REF_5 = @DOC_REF_5		,
			FECHA_TRANSACCION = @FECHA_TRANSACCION
	WHERE  COD_CIA = @COD_CIA AND
        COMPANIA_VENTA_3 = @COMPANIA_VENTA_3 AND
        ALMACEN_VENTA = @ALMACEN_VENTA AND
        TIPO_MOVIMIENTO = @TIPO_MOVIMIENTO AND
        TIPO_DOCUMENTO = @TIPO_DOCUMENTO AND
        NRO_DOCUMENTO = @NRO_DOCUMENTO AND
        COD_ITEM_2 = @COD_ITEM_2 

END

GO
--ELIMINA DATOS
CREATE OR ALTER PROCEDURE  SP_MOV_INVENTARIO_ELIMINAR

	@COD_CIA		  varchar(5)  ,
	@COMPANIA_VENTA_3 varchar(5)  ,
	@ALMACEN_VENTA	  varchar(10) ,
	@TIPO_MOVIMIENTO  varchar(2)  ,
	@TIPO_DOCUMENTO   varchar(2)  ,
	@NRO_DOCUMENTO    varchar(50) ,
	@COD_ITEM_2		  varchar(50)

AS

BEGIN
	SET NOCOUNT ON;

	DELETE FROM dbo.MOV_INVENTARIO WHERE  COD_CIA = @COD_CIA AND
        COMPANIA_VENTA_3 = @COMPANIA_VENTA_3 AND
        ALMACEN_VENTA = @ALMACEN_VENTA AND
        TIPO_MOVIMIENTO = @TIPO_MOVIMIENTO AND
        TIPO_DOCUMENTO = @TIPO_DOCUMENTO AND
        NRO_DOCUMENTO = @NRO_DOCUMENTO AND
        COD_ITEM_2 = @COD_ITEM_2 

END


exec SP_MOV_INVENTARIO_OBTENER @COD_CIA=N'CIA01',@COMPANIA_VENTA_3=N'CV01',@ALMACEN_VENTA=N'ALM001',@TIPO_MOVIMIENTO=N'IN',@TIPO_DOCUMENTO=N'FA',@NRO_DOCUMENTO=N'DOC000001',@COD_ITEM_2=N'ITEM002'

SELECT * FROM dbo.MOV_INVENTARIO 